title = "Master Project"

[owner]
name = "Uladzilsau Darhevich"
dob = 1991-01-28

[dev]
api_endpoint = "https://api.coingecko.com/api/v3"
path_coin_list = "data/coin_list"
path_raw_data = "data/raw"
path_to_logs = "logs/"
path_to_datalake = "data/datalake"
aws_profile = "master"
aws_bucket = "kosmobiker-masterproject"
lambda_func_name = "Kosmo_Test_Lambda_Function"
schema_name = "u.darhevich-schema"
schema_version = "0.2-test"